※ 참고사항
1. 실습 시간에 모든 문제를 해결했을 경우, 강의 종료!

2. 위의 질문에 대해 각자 Cell을 만들어 작성하고, E-campus에 제출시 ipynb 파일로 제출할 것.

3. 첫번째 과제의 제출 기간은 9/22 15:00 까지

4. 기타 질문 사항은 조교에게 문의

문제1 : 강수량과 기온에 따른 날씨의 맑음, 흐림에 대한 유무가 다음 데이터와 같다.

해당 데이터와, KNeighborsClassifier를 사용하여 날씨 정보를 학습하고 예측하는 프로그램을 구성하고 아래 사항에 답하여라

단, Train, Test Data의 비율을 7:3으로 나누어 학습하여라.

1-1) N = 3일 때 분류 모델의 정확도를 구하여라

1-2) N = 3일 때, 강수량이 2.0, 기온이 20.0일 때 날씨는 흐림인가? 맑음인가?

1-3) N = 3일 때, 강수량이 5.0, 기온이 21.0일 때 날씨는 맑음인가? 흐림인가?

1-4) N의 값의 범위가 2~5일 때 가장 정확도가 높은 N의 값이 Train, Test Data로 나누기 전과 차이가 있는지 기술하고, 가장 정확도가 높은 N의 값을 구하여라. 각각의 경우를 Plotting 하고, 그림에 대해 분석하여라

1-5) N = 3일 때, Train, Test Data의 비율을 6:4, 7:3, 8:2로 구분하여 각각 학습하고, 어느 비율에서 가장 높은 정확도를 보이는지 답하여라.




In [76]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn import datasets

# Assigning features and label variables
# First Feature
rain = [0.0, 0.5, 1.0, 7.1, 2.3, 6.1, 3.3, 3.7, 20.0, 2.1, 0.1, 0.3, 0.3, 1.1, 0.5, 4.2, 8.6, 3.0, 5.4, 3.3]

# Second Feature
temp = [23.1, 22.7, 21.9, 16.4, 20.2, 19.2, 19.5, 18.3, 14.2, 21.1, 22.2, 22.3, 22.0, 21.1, 23.0, 20.1, 17.8, 18.9, 18.2, 20.6]

# Label or target varible 0 : 흐림, 1 : 맑음
weather = [1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1]

In [77]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn import datasets
weather_data=[[l,w]for l, w in zip(rain,temp)]


In [78]:
input_arr = np.array(weather_data)
target_arr=np.array(weather)
print(input_arr)
np.random.seed(0)
index=np.arange(20)
np.random.shuffle(index)
train_input=input_arr[index[:14]]
train_target=target_arr[index[:14]]
test_input=input_arr[index[14:]]
test_target=target_arr[index[14:]]
kn=kn.fit(train_input,train_target)
kn.score(test_input,test_target)

[[ 0.  23.1]
 [ 0.5 22.7]
 [ 1.  21.9]
 [ 7.1 16.4]
 [ 2.3 20.2]
 [ 6.1 19.2]
 [ 3.3 19.5]
 [ 3.7 18.3]
 [20.  14.2]
 [ 2.1 21.1]
 [ 0.1 22.2]
 [ 0.3 22.3]
 [ 0.3 22. ]
 [ 1.1 21.1]
 [ 0.5 23. ]
 [ 4.2 20.1]
 [ 8.6 17.8]
 [ 3.  18.9]
 [ 5.4 18.2]
 [ 3.3 20.6]]


0.8333333333333334

In [90]:
kn=KNeighborsClassifier(n_neighbors=4)
kn.fit(weather_data,weather)
kn.score(weather_data,weather)
#정확도의 차이가 존재한다. 2,4일때 가장 정확도가 높다.

0.9

#### kn.predict([[3.0,20.0]])#맑음

In [81]:
kn.predict([[5.0,21.0]])#흐림

array([0])

In [83]:

train_input=input_arr[index[:12]]
train_target=target_arr[index[:12]]
test_input=input_arr[index[12:]]
test_target=target_arr[index[12:]]

kn=kn.fit(train_input,train_target)
kn.score(test_input,test_target)


0.875

In [84]:
train_input=input_arr[index[:16]]
train_target=target_arr[index[:16]]
test_input=input_arr[index[16:]]
test_target=target_arr[index[16:]]

kn=kn.fit(train_input,train_target)
kn.score(test_input,test_target)

#12:8의 비율일때 가장 정확하다.

0.75

실습 문제 2 아래 Cell에 Wine에 대한 정보가 담겨있다. 

해당 데이터와, KNeighborsClassifier를 사용하여 날씨 정보를 학습하고 예측하는 프로그램을 구성하고 아래 사항에 답하여라

단, Train, Test Data의 비율을 7:3으로 나누어 학습하여라.

1-1) N = 3일 때 분류 모델의 정확도를 구하여라.

1-2) N의 값의 범위가 2~5일 때 가장 정확도가 높은 N의 값이 Train, Test Data로 나누기 전과 차이가 있는지 기술하고, 가장 정확도가 높은 N의 값을 구하여라. 각각의 경우를 Plotting 하고, 그림에 대해 분석하여라


1-3) N = 3일 때, Train, Test Data의 비율을 6:4, 7:3, 8:2로 구분하여 각각 학습하고 가장 높은 정확도가 어느 비율인지 기술하여라.

In [38]:
#Load dataset
wine = datasets.load_wine()
print(wine)
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn import datasets



{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [54]:
wine.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [66]:
wine_target=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2]
input_arr = np.array(wine.data)
target_arr=np.array(wine_target)
print(input_arr)
np.random.seed(0)
n = len(wine.data)
r = round(n*(0.7))
index=np.arange(n)
np.random.shuffle(index)
train_input=input_arr[index[:r]]
train_target=target_arr[index[:r]]
test_input=input_arr[index[r:]]
test_target=target_arr[index[r:]]
kn=kn.fit(train_input,train_target)
kn.score(test_input,test_target)


[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


0.7358490566037735

In [67]:
kn=KNeighborsClassifier(n_neighbors=2)
kn.fit(wine.data,wine_target)
kn.score(wine.data,wine_target)

0.8764044943820225

In [68]:
kn=KNeighborsClassifier(n_neighbors=3)
kn.fit(wine.data,wine_target)
kn.score(wine.data,wine_target)

0.8707865168539326

In [69]:
kn=KNeighborsClassifier(n_neighbors=4)
kn.fit(wine.data,wine_target)
kn.score(wine.data,wine_target)

0.8258426966292135

In [71]:
kn=KNeighborsClassifier(n_neighbors=5)
kn.fit(wine.data,wine_target)
kn.score(wine.data,wine_target)

0.7865168539325843

In [74]:
n = len(wine.data)
r = round(n*(0.8))
index=np.arange(n)
np.random.shuffle(index)
train_input=input_arr[index[:r]]
train_target=target_arr[index[:r]]
test_input=input_arr[index[r:]]
test_target=target_arr[index[r:]]
kn=kn.fit(train_input,train_target)
kn.score(test_input,test_target)


0.7222222222222222

In [75]:
n = len(wine.data)
r = round(n*(0.6))
index=np.arange(n)
np.random.shuffle(index)
train_input=input_arr[index[:r]]
train_target=target_arr[index[:r]]
test_input=input_arr[index[r:]]
test_target=target_arr[index[r:]]
kn=kn.fit(train_input,train_target)
kn.score(test_input,test_target)


0.6901408450704225